name: unet_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - aiohttp=3.9.5
  - aiosignal=1.3.1
  - albucore=0.0.9
  - albumentations=1.4.8
  - annotated-types=0.7.0
  - anyio=4.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - astunparse=1.6.3
  - async-lru=2.0.4
  - async-timeout=4.0.3
  - attrs=23.2.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - bleach=4.1.0
  - blinker=1.8.2
  - brotli-python=1.1.0
  - c-ares=1.28.1
  - ca-certificates=2024.6.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.3
  - certifi=2024.6.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - comm=0.2.1
  - contourpy=1.1.1
  - cryptography=42.0.8
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=8.9.7.29
  - cycler=0.12.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - filelock=3.14.0
  - flatbuffers=23.5.26
  - fonttools=4.53.0
  - frozenlist=1.4.1
  - fsspec=2024.6.0
  - gast=0.5.4
  - giflib=5.2.2
  - google-auth=2.30.0
  - google-auth-oauthlib=1.0.0
  - google-pasta=0.2.0
  - grpcio=1.54.3
  - h5py=3.11.0
  - hdf5=1.14.3
  - icu=73.2
  - idna=3.7
  - imageio=2.34.1
  - imgaug=0.4.0
  - importlib-metadata=7.1.0
  - importlib-resources=6.4.0
  - importlib_metadata=7.1.0
  - importlib_resources=6.1.1
  - ipykernel=6.28.0
  - ipython=8.12.2
  - jedi=0.18.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - keras=2.13.1
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lazy-loader=0.4
  - ld_impl_linux-64=2.38
  - libabseil=20230125.3
  - libaec=1.1.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.8.0
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libgrpc=1.54.3
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libprotobuf=3.21.12
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libzlib=1.2.13
  - markdown=3.6
  - markupsafe=2.1.5
  - matplotlib=3.7.5
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mpmath=1.3.0
  - multidict=6.0.5
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - nccl=2.21.5.1
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.1
  - notebook-shim=0.2.3
  - numpy=1.24.4
  - nvidia-cublas-cu12=12.1.3.1
  - nvidia-cuda-cupti-cu12=12.1.105
  - nvidia-cuda-nvrtc-cu12=12.1.105
  - nvidia-cuda-runtime-cu12=12.1.105
  - nvidia-cudnn-cu12=8.9.2.26
  - nvidia-cufft-cu12=11.0.2.54
  - nvidia-curand-cu12=10.3.2.106
  - nvidia-cusolver-cu12=11.4.5.107
  - nvidia-cusparse-cu12=12.1.0.106
  - nvidia-nccl-cu12=2.20.5
  - nvidia-nvjitlink-cu12=12.5.40
  - nvidia-nvtx-cu12=12.1.105
  - oauthlib=3.2.2
  - opencv-python=4.10.0.82
  - opencv-python-headless=4.10.0.82
  - openssl=3.3.1
  - opt_einsum=3.3.0
  - overrides=7.4.0
  - packaging=24.0
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - protobuf=4.21.12
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.6.0
  - pyasn1-modules=0.4.0
  - pycparser=2.22
  - pydantic=2.7.3
  - pydantic-core=2.18.4
  - pygments=2.15.1
  - pyjwt=2.8.0
  - pyopenssl=24.0.0
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - python=3.8.19
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.16.2
  - python-flatbuffers=24.3.25
  - python-json-logger=2.0.7
  - python_abi=3.8
  - pytz=2024.1
  - pyu2f=0.1.5
  - pywavelets=1.4.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - re2=2023.03.02
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - requests-oauthlib=2.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - rsa=4.9
  - scikit-image=0.21.0
  - scikit-learn=1.3.2
  - scipy=1.10.1
  - send2trash=1.8.2
  - setuptools=69.5.1
  - shapely=2.0.4
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.2.0
  - sympy=1.12.1
  - tensorboard=2.13.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.13.1
  - tensorflow-addons=0.21.0
  - tensorflow-base=2.13.1
  - tensorflow-estimator=2.13.1
  - termcolor=2.4.0
  - terminado=0.17.1
  - threadpoolctl=3.5.0
  - tifffile=2023.7.10
  - tinycss2=1.2.1
  - tk=8.6.14
  - tomli=2.0.1
  - torch=2.3.1
  - torchvision=0.18.1
  - tornado=6.3.3
  - tqdm=4.66.4
  - traitlets=5.7.1
  - triton=2.3.1
  - typeguard=2.13.3
  - typing-extensions=4.12.2
  - typing_extensions=4.11.0
  - urllib3=2.2.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.0.3
  - wheel=0.43.0
  - wrapt=1.16.0
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - absl-py==2.1.0
    - aiohttp==3.9.5
    - aiosignal==1.3.1
    - albucore==0.0.9
    - albumentations==1.4.8
    - annotated-types==0.7.0
    - anyio==4.2.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - astunparse==1.6.3
    - async-lru==2.0.4
    - async-timeout==4.0.3
    - attrs==23.2.0
    - Babel==2.11.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.2
    - bleach==4.1.0
    - blinker==1.8.2
    - Brotli==1.1.0
    - cached-property==1.5.2
    - cachetools==5.3.3
    - certifi==2024.6.2
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - comm==0.2.1
    - contourpy==1.1.1
    - cryptography==42.0.8
    - cycler==0.12.1
    - debugpy==1.6.7
    - decorator==5.1.1
    - defusedxml==0.7.1
    - exceptiongroup==1.2.0
    - executing==0.8.3
    - fastjsonschema==2.16.2
    - filelock==3.14.0
    - flatbuffers==24.3.25
    - fonttools==4.53.0
    - frozenlist==1.4.1
    - fsspec==2024.6.0
    - gast==0.5.4
    - google-auth==2.30.0
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - grpcio==1.54.3
    - h5py==3.11.0
    - idna==3.7
    - imageio==2.34.1
    - imgaug==0.4.0
    - importlib_metadata==7.1.0
    - importlib-resources==6.1.1
    - ipykernel==6.28.0
    - ipython==8.12.2
    - jedi==0.18.1
    - Jinja2==3.1.4
    - joblib==1.4.2
    - json5==0.9.6
    - jsonschema==4.19.2
    - jsonschema-specifications==2023.7.1
    - jupyter_client==8.6.0
    - jupyter_core==5.5.0
    - jupyter-events==0.8.0
    - jupyter-lsp==2.2.0
    - jupyter_server==2.10.0
    - jupyter_server_terminals==0.4.4
    - jupyterlab==4.0.11
    - jupyterlab-pygments==0.1.2
    - jupyterlab_server==2.25.1
    - keras==2.13.1
    - kiwisolver==1.4.5
    - lazy_loader==0.4
    - Markdown==3.6
    - MarkupSafe==2.1.5
    - matplotlib==3.7.5
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - mpmath==1.3.0
    - multidict==6.0.5
    - nbclient==0.8.0
    - nbconvert==7.10.0
    - nbformat==5.9.2
    - nest-asyncio==1.6.0
    - networkx==3.1
    - notebook_shim==0.2.3
    - numpy==1.24.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.5.40
    - nvidia-nvtx-cu12==12.1.105
    - oauthlib==3.2.2
    - opencv-python==4.10.0.82
    - opencv-python-headless==4.10.0.82
    - opt-einsum==3.3.0
    - overrides==7.4.0
    - packaging==24.0
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==10.3.0
    - pip==24.0
    - pkgutil_resolve_name==1.3.10
    - platformdirs==3.10.0
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.43
    - protobuf==4.21.12
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.6.0
    - pyasn1_modules==0.4.0
    - pycparser==2.22
    - pydantic==2.7.3
    - pydantic_core==2.18.4
    - Pygments==2.15.1
    - PyJWT==2.8.0
    - pyOpenSSL==24.0.0
    - pyparsing==3.1.2
    - PySocks==1.7.1
    - python-dateutil==2.9.0.post0
    - python-json-logger==2.0.7
    - pytz==2024.1
    - pyu2f==0.1.5
    - PyWavelets==1.4.1
    - PyYAML==6.0.1
    - pyzmq==25.1.2
    - referencing==0.30.2
    - requests==2.32.3
    - requests-oauthlib==2.0.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.10.6
    - rsa==4.9
    - scikit-image==0.21.0
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - Send2Trash==1.8.2
    - setuptools==69.5.1
    - shapely==2.0.4
    - six==1.16.0
    - sniffio==1.3.0
    - soupsieve==2.5
    - stack-data==0.2.0
    - sympy==1.12.1
    - tensorboard==2.13.0
    - tensorboard-data-server==0.7.0
    - tensorflow==2.13.1
    - tensorflow-addons==0.21.0
    - tensorflow-estimator==2.13.0
    - termcolor==2.4.0
    - terminado==0.17.1
    - threadpoolctl==3.5.0
    - tifffile==2023.7.10
    - tinycss2==1.2.1
    - tomli==2.0.1
    - torch==2.3.1
    - torchvision==0.18.1
    - tornado==6.3.3
    - tqdm==4.66.4
    - traitlets==5.7.1
    - triton==2.3.1
    - typeguard==2.13.3
    - typing_extensions==4.11.0
    - urllib3==2.2.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - Werkzeug==3.0.3
    - wheel==0.43.0
    - wrapt==1.16.0
    - yarl==1.9.4
    - zipp==3.19.2
